# SOURCES
# https://starship.rs/config
# https://starship.rs/presets/nerd-font.html#configuration

# DEBUG via:
# starship explain
# STARSHIP_LOG=trace

"$schema" = 'https://starship.rs/config-schema.json'

# Timeout for commands executed by starship (ms)
command_timeout = 1000

# newline between commands
add_newline = true

# Control order
format="""
$hostname$directory$git_branch$git_status$custom$all
"""

[character]
success_symbol = "[-❯](green)"
error_symbol = "[-DOH!-❯](red)"

[custom.rancher]
command = 'rdctl api /v1/settings | jq -r .containerEngine.name'
format = '\(#[$output]($style)\) '
when = true
style = 'bold yellow'
description = 'Rancher Container Engine (custom)'

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = false

[hostname]
ssh_only = false
format = "[@$hostname](green bold)"
disabled = false

# truncation length works backwards (i.e., cwd > parent > parent ...)
[directory]
truncation_length = 15
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
truncation_length = 25
truncation_symbol = ''

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'

[git_commit]
commit_hash_length = 4

[env_var.SHELL]
variable = "SHELL"
default = "unknown shell"
disabled = true

[cmd_duration]
min_time = 500
format = '[$duration](bold yellow)'

# Show python version starting with venv
[python]
python_binary = ["./venv/bin/python", "python3", "python", "python2"]

[aws]
format = '\(AWS:[($profile )({$region})]($style)\) '
style = 'bold blue'
[aws.region_aliases]
ap-southeast-2 = 'AU'
us-east-1 = 'VA'
us-east-2 = 'OH'
eu-west-1 = 'Ire'
[aws.profile_aliases]
Administrator_FullAccess-434875166128 = 'Main-Full'
Administrator_Readonly-434875166128 = 'Main-RO'
Administrator_FullAccess-612430976833 = 'CDE-Full'
Administrator_Readonly-612430976833 = 'CDE-RO'
Administrator_FullAccess-567795905116 = 'Token-Full'
Administrator_Readonly-567795905116 = 'Token-Full'
